# Configuration of Hugo
# Guide: https://docs.hugoblox.com/tutorial/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: "김시현 - 컴퓨터공학부 포트폴리오 | AI 개발자" # Website name
baseURL: "https://sirung2.github.io/" # Website URL

############################
## PAGE OPTIONS
############################

cascade:
  # Blog post options
  - _target:
      path: /post/**
    editable: true
    reading_time: true
    commentable: true
    show_related: true
    show_breadcrumb: true

############################
## LANGUAGE
############################

defaultContentLanguage: ko
hasCJKLanguage: true
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
pagination:
  pagerSize: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  authors: "/author/:slug/"
  tags: "/tag/:slug/"
  categories: "/category/:slug/"
disableAliases: true
outputs:
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  author: authors
# 검색 최적화를 위한 추가 설정
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: github
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
minify:
  _merge: deep

# 검색 최적화 설정
params:
  search:
    enable: true
    placeholder: "김시현, 전북대학교 검색..."
    show_result_count: true
    content_lang: ["ko"]
  seo:
    title: "김시현 - 컴퓨터공학부 포트폴리오 | AI 개발자"
    description: "전북대학교 컴퓨터공학부 김시현의 포트폴리오 사이트. AI 개발자, EdTech 전문가, 오픈소스 기여자. 김시현, 전북대학교 김시현, 컴퓨터공학부 김시현"
    keywords:
      [
        "김시현",
        "전북대학교 김시현",
        "컴퓨터공학부 김시현",
        "김시현 포트폴리오",
        "전북대 AI 개발자",
        "EdTech 전문가",
        "오픈소스 기여자",
      ]
    author: "김시현"
    twitter:
      site: "@SiHyeonKim"
      creator: "@SiHyeonKim"
    openGraph:
      type: website
      locale: ko_KR
      site_name: "김시현 포트폴리오"
